---
  - name: Class 12.3 Activity 3
    hosts: webservers
    become: true
    tasks:
    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Python Docker module
      pip:
        name: docker
        state: present

    - name: Download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
---
- name: Class 13.1
  hosts: elk
  become: true
  tasks:
  - name: set vm.max_map_count to 262144 in sysctl
    sysctl: name={{ item.key }} value={{ item.value }}
    with_items:
      - { key: "vm.max_map_count", value: "262144" }

  - name: Install docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install PIP 3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker Python module
    pip:
      name: docker
      state: present

  - name: download and launch docker elk container
    docker_container:
     name: elk
     image: sebp/elk:761
     state: started
     published_ports:
       - 5601:5601
       - 9200:9200
       - 5044:5044

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
      state: restarted

---
- name: Setup filebeats
  hosts: webservers
  remote_user: ansibleadmin

  tasks:
  - name: Create /home/ansibleadmin/files folder on managed nodes
    file:
      path: /home/ansibleadmin/files
      state: directory

  - name: Copy deb file from Ansible Server to managed node
    ansible.builtin.copy:
      src: /etc/ansible/files/filebeat-7.4.0-amd64.deb
      dest: /home/ansibleadmin/filebeat-7.4.0-amd64.deb
      owner: ansibleadmin
      group: ansibleadmin
      mode: u=rw,g=r,o=r
      remote_src: no

  - name: Copy deb file from Ansible Server to managed node
    ansible.builtin.copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /home/ansibleadmin/filebeat.yml
      owner: ansibleadmin
      group: ansibleadmin
      mode: u=rw,g=r,o=r
      remote_src: no

  - name: copy /home/ansibleadmin/filebeat.yml to /etc/filebeat/filebeat.yml
    command: sudo cp /home/ansibleadmin/filebeat.yml /etc/filebeat/filebeat.yml

  - name: set owner of /etc/filebeat/filebeat.yml
    command: sudo chown root:root /etc/filebeat/filebeat.yml

  - name: sudo dpkg -i filebeat-7.4.0-amd64.deb
    command: sudo dpkg -i filebeat-7.4.0-amd64.deb

  - name: sudo filebeat modules enable system
    command: sudo filebeat modules enable system

  - name: sudo filebeat setup
    command: sudo filebeat setup

  - name: sudo service filebeat start
    command: sudo service filebeat start

  - name: Enable filebeat
    become: yes
    become_method: sudo
    service:
      name: filebeat
      enabled: yes
      state: started
      use: service
---
- name: Setup metricbeats
  hosts: webservers
  remote_user: ansibleadmin

  tasks:
  - name: Create /home/ansibleadmin/files folder on managed nodes
    file:
      path: /home/ansibleadmin/files
      state: directory

  - name: Create /etc/metricbeat
    become: yes
    file:
      path: /etc/metricbeat
      state: directory
      owner: root

  - name: Copy metricbeat-7.4.0-amd64.deb metric from Ansible Server to managed node
    ansible.builtin.copy:
      src: /etc/ansible/files/metricbeat-7.4.0-amd64.deb
      dest: /home/ansibleadmin/files/metricbeat-7.4.0-amd64.deb
      owner: ansibleadmin
      group: ansibleadmin
      mode: u=rw,g=r,o=r
      remote_src: no

  - name: Copy metricbeat-config.yml from Ansible Server to managed node
    ansible.builtin.copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /home/ansibleadmin/files/metricbeat.yml
      owner: ansibleadmin
      group: ansibleadmin
      mode: u=rw,g=r,o=r
      remote_src: no

  - name: copy /home/ansibleadmin/files/metricbeat.yml to /etc/metricbeat/metricbeat.yml
    command: sudo cp -p /home/ansibleadmin/files/metricbeat.yml /etc/metricbeat/metricbeat.yml

  - name: set owner of /etc/metricbeat/metricbeat.yml
    command: sudo chown root:root /etc/metricbeat/metricbeat.yml

  - name: fix
    command: sudo rm -f /var/lib/dpkg/lock

  - name: install
    command: sudo apt-get -o DPkg::Options::="--force-confnew" -y install /home/ansibleadmin/metricbeat-7.4.0-amd64.deb

  - name: sudo metricbeat modules enable system
    command: sudo metricbeat modules enable system

  - name: sudo metricbeat setup
    command: sudo metricbeat setup

  - name: sudo service metricbeat start
    command: sudo service metricbeat start

  - name: Enable metricbeat
    become: yes
    become_method: sudo
    service:
      name: metricbeat
      enabled: yes
      state: started
      use: service